export const META = {
  title: "Cafeit - Real-time cafe seat availability",
  siteName: "Cafeit",
  description: "Check real-time cafe seat availability and use it conveniently!",
  keyword: [
    "real-time cafe",
    "cafe seats",
    "cafe availability",
    "cafeit",
    "cafe reservation",
    "find cafe",
    "real-time availability",
    "cafe seating",
    "cafe usage",
    "cafe information",
    "cafe service",
  ],
  url: "https://cafeit.com",
  googleVerification: "CgyfsknTnwmw-3MVu_AGzdeVCqRY3d2VTrQWaCumLfQ",
  naverVerification: "6e541c9717d6614e8ee55b0d67f4eb82bcdfd16c",
  ogImage: "/favicon.png",
} as const;
